// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDqPYnVgZriI7n8P3zIQQSjXHKsNBf1Cg',
    appId: '1:431259803667:web:d2207f08eb7220f67fdfe6',
    messagingSenderId: '431259803667',
    projectId: 'presenteapp-97f7f',
    authDomain: 'presenteapp-97f7f.firebaseapp.com',
    storageBucket: 'presenteapp-97f7f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp8UCcovMpruGR3W4Tt4nvsvqG0AdUxes',
    appId: '1:431259803667:android:cdff39c796f643b77fdfe6',
    messagingSenderId: '431259803667',
    projectId: 'presenteapp-97f7f',
    storageBucket: 'presenteapp-97f7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0MJIJcVlbJU8wG6-p_g0gqcVBpp3JGRM',
    appId: '1:431259803667:ios:f6fa5955745d8cda7fdfe6',
    messagingSenderId: '431259803667',
    projectId: 'presenteapp-97f7f',
    storageBucket: 'presenteapp-97f7f.firebasestorage.app',
    iosBundleId: 'com.example.tesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0MJIJcVlbJU8wG6-p_g0gqcVBpp3JGRM',
    appId: '1:431259803667:ios:f6fa5955745d8cda7fdfe6',
    messagingSenderId: '431259803667',
    projectId: 'presenteapp-97f7f',
    storageBucket: 'presenteapp-97f7f.firebasestorage.app',
    iosBundleId: 'com.example.tesis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDqPYnVgZriI7n8P3zIQQSjXHKsNBf1Cg',
    appId: '1:431259803667:web:013147eba8023ce57fdfe6',
    messagingSenderId: '431259803667',
    projectId: 'presenteapp-97f7f',
    authDomain: 'presenteapp-97f7f.firebaseapp.com',
    storageBucket: 'presenteapp-97f7f.firebasestorage.app',
  );
}
